title: Lakshmi Subbramanian
author: GitHub User
email: hello@lakshmix.xyz
description: > # this means to ignore newlines until "baseurl:"
    Welcome to Lakshmi's homepage on GitHub. Here, you will see ways to connect with her online.
Thanks for stopping by. 
# social links
twitter_username: simhskal # DO NOT include the @ character, or else the build will fail!
github_username:  simhskal # DO NOT include the @ character, or else the build will fail!

theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
